# Generated by Django 4.0.3 on 2022-03-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('Scheduled', 0), ('Live', 1), ('Finished', 2)])),
                ('status_note', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('b_place', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=64, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('players', models.ManyToManyField(to='main.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('overs', models.FloatField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='main.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='main.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.venue'),
        ),
        migrations.CreateModel(
            name='FallOfWicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fow', models.TextField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out', models.CharField(blank=True, max_length=255, null=True)),
                ('maiden', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('wicket', models.IntegerField(blank=True, null=True)),
                ('wides', models.IntegerField(blank=True, null=True)),
                ('no_balls', models.IntegerField(blank=True, null=True)),
                ('econs', models.IntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out', models.CharField(blank=True, max_length=255, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('balls', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
