# Generated by Django 4.0.3 on 2022-04-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=25)),
                ('status_note', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('scorecard_url', models.TextField(blank=True, null=True)),
                ('commentary_url', models.TextField(blank=True, null=True)),
                ('squads_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('b_date', models.DateField(blank=True, null=True)),
                ('b_place', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=64, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('players', models.ManyToManyField(to='main.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting', models.TextField()),
                ('bowling', models.TextField()),
                ('fall_of_wickets', models.TextField(blank=True)),
                ('inning', models.CharField(blank=True, max_length=10)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='main.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='main.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.venue'),
        ),
        migrations.CreateModel(
            name='FallOfWicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fow', models.TextField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler', models.CharField(max_length=64)),
                ('overs', models.CharField(blank=True, max_length=6, null=True)),
                ('maidens', models.CharField(blank=True, max_length=6, null=True)),
                ('runs', models.CharField(blank=True, max_length=6, null=True)),
                ('wickets', models.CharField(blank=True, max_length=6, null=True)),
                ('wides', models.CharField(blank=True, max_length=6, null=True)),
                ('no_balls', models.CharField(blank=True, max_length=6, null=True)),
                ('econs', models.CharField(blank=True, max_length=6, null=True)),
                ('active', models.BooleanField(default=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batsman', models.CharField(max_length=64)),
                ('out', models.CharField(blank=True, max_length=64, null=True)),
                ('runs', models.CharField(blank=True, max_length=6, null=True)),
                ('balls', models.CharField(blank=True, max_length=6, null=True)),
                ('fours', models.CharField(blank=True, max_length=6, null=True)),
                ('sixes', models.CharField(blank=True, max_length=6, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runrate', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.CharField(blank=True, max_length=64, null=True)),
                ('overs', models.CharField(blank=True, max_length=64, null=True)),
                ('full_score', models.CharField(blank=True, max_length=64, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'unique_together': {('team', 'fixture')},
            },
        ),
    ]
