# Generated by Django 4.0.3 on 2022-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='commentary_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='scorecard_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='squads_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
