# Generated by Django 4.0.3 on 2022-04-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inning',
            unique_together={('fixture', 'team', 'inning')},
        ),
    ]
