# Generated by Django 4.0.1 on 2022-01-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('status_note', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('scorecard_url', models.CharField(blank=True, max_length=255, null=True)),
                ('commentary_url', models.CharField(blank=True, max_length=255, null=True)),
                ('squads_url', models.CharField(blank=True, max_length=255, null=True)),
                ('team_a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('team_b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
    ]
