# Generated by Django 4.0.3 on 2022-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inning_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inning',
            unique_together=set(),
        ),
    ]
