# Generated by Django 4.0.1 on 2022-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_team_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team_a_id',
            new_name='team_a',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_b_id',
            new_name='team_b',
        ),
        migrations.AlterField(
            model_name='team',
            name='image_url',
            field=models.CharField(default='https://images.news18.com/static_news18/pix/ibnhome/news18/default-flag.jpg', max_length=255),
        ),
    ]
