# Generated by Django 4.0.3 on 2022-03-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_fixture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.series'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Live'), (2, 'Finished')]),
        ),
    ]
