# Generated by Django 4.0.3 on 2022-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fixture_series_alter_fixture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='overs',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('team', 'fixture')},
        ),
    ]
